############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Veranstaltungen"
url = "veranstaltungen/"
weight = 2

[[main]]
name = "Aktuelles"
url = "aktuelles/"
weight = 3
  
[[main]]
name = "Kontakt"
url = "kontakt/"
weight = 4


# footer menu
[[footer]]
name = "Veranstaltungen"
url = "veranstaltungen/"
weight = 2

[[footer]]
name = "Aktuelles"
url = "aktuelles/"
weight = 3

[[footer]]
name = "Kontakt"
url = "kontakt/"
weight = 4
